version: "3.8"
services:
  server:
    build: .
    env_file:
      - .env
    command: python ./storage_server.py
    ports:
      - 5555:5555
    stdin_open: true
    tty: true

  client:
    build: .
    env_file:
      - .env
    command: python ./weather_station.py
    stdin_open: true
    tty: true